### ISSUE TITLE
Retrieving the keys locally for decryption

### ISSUE THREAD

**Issue by Vivekmauli14** [b-long/opentdf-python-sdk#15]
Hi,

Thank you for your update last month. I find this project quite interesting and am hoping to get some assistance, particularly with key object retrieval. I’m trying to store the original decryption key and rewrap it with my encryption logic, which uses a password for decryption. This approach would allow me to provide access to the file on other networks where my IDP server is not accessible.

Do you have any suggestions on how to achieve this? I’ve been trying to learn more about the KAS project, but I’m relatively new to Go programming, and the documentation isn’t very clear.

Thanks for your help!

Thanks,
Vivek

**Comment by b-long** [comment]
Hi @Vivekmauli14 , I'm not sure if the above is possible in the Go SDK.  Having that functionality in the Go SDK would be a prerequisite to exposing it to this Python SDK , since we're essentially a binding/wrapper.

If you're able to find such a function in the Go SDK ( https://github.com/opentdf/platform/tree/main/sdk ), please let me know.  For now, I'll close this issue, as I don't believe it's possible.
